# Generated by Django 5.0.4 on 2024-05-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "idHotel",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("nombreEstablecimiento", models.CharField(max_length=100)),
                ("horaCheckIn", models.TimeField()),
                ("horaCheckOut", models.TimeField()),
                ("petFriendly", models.BooleanField()),
                ("servicio", models.CharField(max_length=100)),
                (
                    "numeroInterior",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("numeroExterior", models.IntegerField()),
                ("colonia", models.CharField(max_length=100)),
                ("calle", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
            ],
        ),
    ]
